class_name HeroRoster
extends RefCounted
const HEROES := [
	{'id':'dart','name':'SOLSTICE','title':'THE SKY FORGE','role':'POWERED FLIGHT','color':'#f3a461','secondary':'#66dcca','art':'res://assets/roster/solstice.png','power':'forge','demo':'Flight / energy lance','story':'Built in a storm-battered sky foundry. Every turbine strike turns momentum into brilliant force.','ability':'AERIAL FORGE','ability_text':'A turbine ascent followed by a focused energy-lance strike.','trait':'PRECISION + FLIGHT','game':'jetpack_test_lab'},
	{'id':'bolt','name':'VECTOR','title':'THE GRAVITY RUNNER','role':'KINETIC ACROBAT','color':'#e58cbc','secondary':'#67d5cc','art':'res://assets/roster/vector.png','power':'tether','demo':'Gravity ribbon / aerial dash','story':'She catches the city on gravity ribbons, then releases it one impossible leap at a time.','ability':'RIBBON SLING','ability_text':'Anchor a gravity ribbon and whip through a curved aerial dash.','trait':'AGILITY + MOMENTUM','game':'skyline_jumper'},
	{'id':'echo','name':'UMBRA','title':'THE LAST NIGHTWATCH','role':'TACTICAL STEALTH','color':'#a2a9dc','secondary':'#81d9ad','art':'res://assets/roster/umbra.png','power':'stealth','demo':'Smoke veil / tactical strike','story':'A quiet guardian with a sharp mind. Smoke, misdirection and one decisive counter end the fight.','ability':'NIGHT VEIL','ability_text':'Dissolve into smoke, mark a target and reappear with a tactical strike.','trait':'CONTROL + COUNTER','game':'shadow_armor_duel'},
	{'id':'frost','name':'PRISM','title':'THE DIMENSION WEAVER','role':'DIMENSIONAL POWER','color':'#b8a0ec','secondary':'#8bddc2','art':'res://assets/roster/prism.png','power':'rift','demo':'Prismatic gate / shard burst','story':'She folds the space between worlds into impossible geometry. Nothing is where you expect it to be.','ability':'PRISMATIC GATE','ability_text':'Open a faceted gate and release a constellation of crystalline shards.','trait':'SPACE + STRATEGY','game':'laser_reflect'}
]
static func hero(index: int) -> Dictionary: return HEROES[posmod(index,HEROES.size())]
