name: Deploy Web
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.1
          use-dotnet: false
          include-templates: true
      - name: Import
        run: godot --headless --import --path .
      - name: Export Web
        run: godot --headless --path . --export-release "Web" "build/web/index.html"
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
